### ISSUE TITLE
[Functionality] JSON Editor

### ISSUE THREAD

**Issue by idantene** [unmock/unmock-vscode-plugin#1]
Recognize json files and synchronize their edits with the unmock cloud via POST requests.

Requirements/questions:
- Each mock file should have a corresponding unmock _metadata_ file, so we don't mess with  irrelevant json files.
- Do we assume the mock folder is statically named (i.e. always called `.unmock` and mocks are always saved under `.unmock/save/`)? Or do we scan for all json files (the latter is the way it's done now)
- A persistence layer for the plugin, saving the refresh token so that one can call POST with the new data. :arrow_right: Should we allow posting to `/y/`?

Implementations:
- [x] Add an unmock view container that will open a _mock explorer_
![image](https://user-images.githubusercontent.com/12184618/54674121-6c462700-4b04-11e9-8b52-4bd6becc20ca.png)
- [x] Synchronize when editing a json file that's opened from the mock explorer
- [x] Add a small persistence layer
